config/routes.rb
Rails.application.routes.draw do

	resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy]
	def index
	end

	def new
		@posts = Post.new
	end

	def create
		@posts = Post.new post_params

		if @posts.save
			redirect_to @posts, notice:"you did it"
		else
			render 'new', notice:"couldnt save"
		end
	end

	def show
		
	end

	def edit
	end

	def update
		if @posts.update post_params
			redirect_to @posts, notice: "article updated"
		else 
			render 'edit'	
		end
	end

	def destroy
		@posts.destroy
		redirect_to posts_path
	end


	private

	def post_params
		params.require(:post).permit(:title, :content)
	end

	def find_post
		@posts = Post.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_form.html.erb
<%= form_for @posts do |f| %>
<% if @posts.errors.any? %>
<h2><%= pluralize(@posts.errors.count, "error") %>, couldnt save</h2>
<ul>
	<% @posts.errors.fill_message do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %>
<br>
<br>
	<%= f.label :content, "write here" %>
	<%= f.text_area :content %>
<br>
<br>

<%= f.submit %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogPractice</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_for @posts do |f| %>
<% if @posts.errors.any? %>
<h2><%= pluralize(@posts.errors.count, "error") %>, couldnt save</h2>
<ul>
	<% @posts.errors.fill_message do |msg| %>
	<li><%= msg %></li>
	<% end %>
</ul>
<% end %>
	<%= f.label :title %>
	<%= f.text_field :title %>
<br>
<br>
	<%= f.label :content, "write here" %>
	<%= f.text_field :content %>
<br>
<br>

<%= f.submit %>

<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<h1>This is post page</h1>

app/views/posts/new.html.erb
<h1>New Post</h1>
<%= render 'form' %>

app/views/posts/show.html.erb
<%= @posts.title %>
<br>
<br>
<%= @posts.content %>

<br>
<br>

<%= link_to "edit", edit_post_path(@posts) %>
<%= link_to "delete", post_path(@posts), method: :delete, data: {confirm: "are you sure?"}  %>	